// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: transaction.proto

#include "transaction.pb.h"
#include "transaction.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace transaction {

static const char* TransactionService_method_names[] = {
  "/transaction.TransactionService/AddTransaction",
};

std::unique_ptr< TransactionService::Stub> TransactionService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TransactionService::Stub> stub(new TransactionService::Stub(channel, options));
  return stub;
}

TransactionService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_AddTransaction_(TransactionService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TransactionService::Stub::AddTransaction(::grpc::ClientContext* context, const ::transaction::TransactionJsonRequest& request, ::transaction::TransactionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::transaction::TransactionJsonRequest, ::transaction::TransactionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AddTransaction_, context, request, response);
}

void TransactionService::Stub::async::AddTransaction(::grpc::ClientContext* context, const ::transaction::TransactionJsonRequest* request, ::transaction::TransactionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::transaction::TransactionJsonRequest, ::transaction::TransactionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddTransaction_, context, request, response, std::move(f));
}

void TransactionService::Stub::async::AddTransaction(::grpc::ClientContext* context, const ::transaction::TransactionJsonRequest* request, ::transaction::TransactionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddTransaction_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::transaction::TransactionResponse>* TransactionService::Stub::PrepareAsyncAddTransactionRaw(::grpc::ClientContext* context, const ::transaction::TransactionJsonRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::transaction::TransactionResponse, ::transaction::TransactionJsonRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AddTransaction_, context, request);
}

::grpc::ClientAsyncResponseReader< ::transaction::TransactionResponse>* TransactionService::Stub::AsyncAddTransactionRaw(::grpc::ClientContext* context, const ::transaction::TransactionJsonRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddTransactionRaw(context, request, cq);
  result->StartCall();
  return result;
}

TransactionService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TransactionService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TransactionService::Service, ::transaction::TransactionJsonRequest, ::transaction::TransactionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TransactionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::transaction::TransactionJsonRequest* req,
             ::transaction::TransactionResponse* resp) {
               return service->AddTransaction(ctx, req, resp);
             }, this)));
}

TransactionService::Service::~Service() {
}

::grpc::Status TransactionService::Service::AddTransaction(::grpc::ServerContext* context, const ::transaction::TransactionJsonRequest* request, ::transaction::TransactionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace transaction

